"""Protocol for the offline Lambda Cloud client boundary."""

from __future__ import annotations

from typing import Protocol

from decodilo.lambda_cloud.api_models import (
    LambdaFilesystem,
    LambdaImage,
    LambdaInstance,
    LambdaInstanceType,
    LambdaQuota,
    LambdaRegion,
    LambdaSSHKey,
    LambdaUsageEstimate,
)


class LambdaCloudClient(Protocol):
    """Provider-neutral client shape for future Lambda integration."""

    def list_instance_types(self) -> list[LambdaInstanceType]: ...

    def list_regions(self) -> list[LambdaRegion]: ...

    def list_images(self) -> list[LambdaImage]: ...

    def list_ssh_keys(self) -> list[LambdaSSHKey]: ...

    def list_filesystems(self) -> list[LambdaFilesystem]: ...

    def list_instances(self) -> list[LambdaInstance]: ...

    def get_instance(self, instance_id: str) -> LambdaInstance: ...

    def get_quota(self) -> LambdaQuota: ...

    def get_usage_estimate(self) -> LambdaUsageEstimate: ...

    def launch_instance(self, *args: object, **kwargs: object) -> None: ...

    def terminate_instance(self, *args: object, **kwargs: object) -> None: ...

    def restart_instance(self, *args: object, **kwargs: object) -> None: ...

    def create_ssh_key(self, *args: object, **kwargs: object) -> None: ...

    def delete_ssh_key(self, *args: object, **kwargs: object) -> None: ...

    def create_filesystem(self, *args: object, **kwargs: object) -> None: ...

    def delete_filesystem(self, *args: object, **kwargs: object) -> None: ...
