"""Non-executable M051B command preview generated by M051A."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from decodilo.lambda_cloud.m051_arming_gate_check import (
    load_lambda_m051_arming_gate_check,
)
from decodilo.lambda_cloud.m051_exact_command_binding import (
    M051_OPERATOR_CONFIRMATION_BILLABLE,
    M051_OPERATOR_CONFIRMATION_TERMINATE,
)

LambdaM051ArmingCommandPreviewStatus = Literal[
    "ready_for_future_m051b_one_shot_metadata_bootstrap",
    "blocked",
]


class LambdaM051ArmingCommandPreview(BaseModel):
    model_config = ConfigDict(frozen=True)

    report_schema_version: int = 1
    preview_status: LambdaM051ArmingCommandPreviewStatus
    executable: bool = False
    selected_candidate: str | None = None
    selected_region: str | None = None
    command_preview: list[str] = Field(default_factory=list)
    statement: str = "M051A does not execute this command."
    raw_ssh_key_name_present: bool = False
    secret_like_value_present: bool = False
    blockers: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    launch_ready: bool = False
    launch_allowed: bool = False
    billable_action_performed: bool = False
    real_mutation_enabled: bool = False

    @model_validator(mode="after")
    def _validate_preview(self) -> LambdaM051ArmingCommandPreview:
        if (
            self.executable
            or self.launch_ready
            or self.launch_allowed
            or self.billable_action_performed
            or self.real_mutation_enabled
            or self.raw_ssh_key_name_present
            or self.secret_like_value_present
        ):
            raise ValueError("M051 arming command preview must remain non-executable")
        if self.preview_status != "blocked" and self.blockers:
            raise ValueError("ready M051 command preview cannot have blockers")
        return self

    def to_json(self) -> str:
        return json.dumps(self.model_dump(mode="json"), indent=2, sort_keys=True) + "\n"


def build_lambda_m051_arming_command_preview_from_paths(
    *,
    arming_gate: str | Path,
) -> LambdaM051ArmingCommandPreview:
    gate = load_lambda_m051_arming_gate_check(arming_gate)
    blockers = list(gate.blockers)
    if not gate.arming_gate_passed:
        blockers.append("m051_arming_gate_not_passed")
    command = _command_preview() if not blockers else []
    command_text = " ".join(command)
    if "launch_ready=true" in command_text or "launch_allowed=true" in command_text:
        blockers.append("forbidden_launch_flag_present")
    return LambdaM051ArmingCommandPreview(
        preview_status=(
            "ready_for_future_m051b_one_shot_metadata_bootstrap"
            if not blockers
            else "blocked"
        ),
        selected_candidate=gate.selected_candidate,
        selected_region=gate.selected_region,
        command_preview=command,
        blockers=sorted(set(blockers)),
        warnings=[
            "M051A does not execute this command.",
            "raw SSH key name and credentials are intentionally absent",
        ],
    )


def _command_preview() -> list[str]:
    return [
        "python",
        "-m",
        "decodilo.cli",
        "lambda",
        "m029",
        "run",
        "--env-file",
        ".env",
        "--env-key",
        "LAMBDA_API_KEY",
        "--m051-bootstrap-authorization",
        "/tmp/decodilo-lambda-m051-bootstrap-authorization.json",
        "--m051-metadata-plan",
        "/tmp/decodilo-lambda-m051-metadata-bootstrap-plan.json",
        "--m051-bootstrap-execution-gate-check",
        "/tmp/decodilo-lambda-m051-bootstrap-execution-gate-check.json",
        "--m051-no-mutation-no-ssh-audit",
        "/tmp/decodilo-lambda-m051-no-mutation-no-ssh-audit.json",
        "--m051-bootstrap-runbook-preview",
        "/tmp/decodilo-lambda-m051-bootstrap-runbook-preview.json",
        "--m050-report",
        "/tmp/decodilo-lambda-m050-report.json",
        "--m051-one-shot-arming",
        "/tmp/decodilo-lambda-m051-one-shot-arming.json",
        "--m051-reviewer-bridge",
        "/tmp/decodilo-lambda-m051-reviewer-bridge.json",
        "--m051-artifact-binding",
        "/tmp/decodilo-lambda-m051-artifact-binding.json",
        "--m051-arming-gate",
        "/tmp/decodilo-lambda-m051-arming-gate-check.json",
        "--ssh-key-selection",
        "/tmp/decodilo-lambda-strand-ssh-key-selection.json",
        "--response-loss-controls",
        "/tmp/decodilo-lambda-strand-response-loss-controls.json",
        "--workdir",
        "/tmp/decodilo-lambda-m051",
        "--execute-real-launch",
        "--confirm-billable-action",
        M051_OPERATOR_CONFIRMATION_BILLABLE,
        "--confirm-terminate-required",
        M051_OPERATOR_CONFIRMATION_TERMINATE,
    ]


def load_lambda_m051_arming_command_preview(
    path: str | Path,
) -> LambdaM051ArmingCommandPreview:
    return LambdaM051ArmingCommandPreview.model_validate_json(
        Path(path).read_text(encoding="utf-8")
    )


def write_lambda_m051_arming_command_preview(
    path: str | Path,
    report: LambdaM051ArmingCommandPreview,
) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(report.to_json(), encoding="utf-8")
